<a href="https://colab.research.google.com/github/harshdhiman7/SIDTM-PDS/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create NumPy array


In [52]:
import numpy as np

# Creating an array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## Creating an array of zeros

In [53]:
arr_zeros = np.zeros((3, 4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Creating an array of ones

In [54]:
arr_ones = np.ones((2, 3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


# Creating an empty array

In [55]:
arr_empty = np.empty((2, 2))
print(arr_empty)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]


# Creating a full array with a specified value

In [56]:
arr_full = np.full((2, 3), 7)
print(arr_full)

[[7 7 7]
 [7 7 7]]


# Creating an array with a range of values

In [57]:
arr_arange = np.arange(0, 10, 2)
print(arr_arange)

[0 2 4 6 8]


# Creating an array with linearly spaced values

In [58]:
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


# Creating an identity matrix


In [59]:
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Creating an array with random values between 0 and 1

In [60]:
arr_rand = np.random.rand(3, 2)
print(arr_rand)

[[0.11758322 0.77400267]
 [0.71520268 0.18627533]
 [0.26609177 0.50167998]]


# Creating an array with random values from a standard normal distribution

In [61]:
arr_randn = np.random.randn(3, 2)
print(arr_randn)

[[ 0.09043435  0.27531577]
 [ 1.08092244 -0.43134942]
 [ 1.7758402   0.44861682]]


# Creating an array with random integers

In [62]:
arr_randint = np.random.randint(0, 10, (3, 3))
print(arr_randint)

[[7 6 0]
 [6 5 9]
 [1 7 9]]


# Creating an array with random samples from a given 1-D array

In [63]:
arr_choice = np.random.choice([1, 2, 3, 4, 5], size=3)
print(arr_choice)

[5 1 2]


#Array Manipulation

In [64]:
import numpy as np

# Creating initial arrays for manipulation
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# np.reshape()
reshaped = np.reshape(arr, (3, 2))
print("Reshaped:\n", reshaped)

# np.ravel()
raveled = np.ravel(arr)
print("Raveled:\n", raveled)

# np.flatten()
flattened = arr.flatten()
print("Flattened:\n", flattened)

# np.transpose()
transposed = np.transpose(arr)
print("Transposed:\n", transposed)

# np.swapaxes()
swapped = np.swapaxes(arr_3d, 0, 2)
print("Swapped axes:\n", swapped)

# np.concatenate()
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated = np.concatenate((arr1, arr2), axis=0)
print("Concatenated:\n", concatenated)

Reshaped:
 [[1 2]
 [3 4]
 [5 6]]
Raveled:
 [1 2 3 4 5 6]
Flattened:
 [1 2 3 4 5 6]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Swapped axes:
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
Concatenated:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [65]:
# np.stack()
stacked = np.stack((arr1, arr2), axis=1)
print("Stacked:\n", stacked)

# np.hstack()
hstacked = np.hstack((arr1, arr2))
print("Horizontally Stacked:\n", hstacked)

Stacked:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]


In [66]:
# np.vstack()
vstacked = np.vstack((arr1, arr2))
print("Vertically Stacked:\n", vstacked)

# np.dstack()
dstacked = np.dstack((arr1, arr2))
print("Depth Stacked:\n", dstacked)

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Depth Stacked:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [67]:
# np.split()
split_arr = np.array([1, 2, 3, 4, 5, 6])
splitted = np.split(split_arr, 3)
print("Split:\n", splitted)

# np.hsplit()
hsplit_arr = np.array([[1, 2, 3], [4, 5, 6]])
hsplitted = np.hsplit(hsplit_arr, 3)
print("Horizontally Split:\n", hsplitted)

# np.vsplit()
vsplit_arr = np.array([[1, 2, 3], [4, 5, 6]])
vsplitted = np.vsplit(vsplit_arr, 2)
print("Vertically Split:\n", vsplitted)

# np.dsplit()
dsplit_arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
dsplitted = np.dsplit(dsplit_arr, 2)
print("Depth Split:\n", dsplitted)

# np.tile()
tiled = np.tile(arr, (2, 2))
print("Tiled:\n", tiled)

# np.repeat()
repeated = np.repeat(arr, 2, axis=0)
print("Repeated:\n", repeated)

Split:
 [array([1, 2]), array([3, 4]), array([5, 6])]
Horizontally Split:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
Vertically Split:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
Depth Split:
 [array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]
Tiled:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]
Repeated:
 [[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [68]:
# np.delete()
deleted = np.delete(arr, 1, axis=0)
print("Deleted:\n", deleted)

# np.insert()
inserted = np.insert(arr, 1, [7, 8, 9], axis=0)
print("Inserted:\n", inserted)

# np.append()
appended = np.append(arr, [[7, 8, 9]], axis=0)
print("Appended:\n", appended)

# np.resize()
resized = np.resize(arr, (3, 2))
print("Resized:\n", resized)

Deleted:
 [[1 2 3]]
Inserted:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
Appended:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Resized:
 [[1 2]
 [3 4]
 [5 6]]


#Array Indexing & Slicing

In [69]:
import numpy as np

# Creating an initial array for manipulation
arr = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# np.take()
taken = np.take(arr, [0, 2, 4])
print("Taken:\n", taken)

# np.put()
np.put(arr, [0, 2], [99, 88])
print("Put:\n", arr)

# np.where()
where = np.where(arr > 20)
print("Where:\n", where)

# np.nonzero()
nonzero = np.nonzero(arr_2d)
print("Nonzero:\n", nonzero)

Taken:
 [10 30 50]
Put:
 [99 20 88 40 50]
Where:
 (array([0, 2, 3, 4]),)
Nonzero:
 (array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [70]:
# np.extract()
condition = arr > 20
extracted = np.extract(condition, arr)
print("Extracted:\n", extracted)

# np.compress()
compressed = np.compress(condition, arr)
print("Compressed:\n", compressed)

Extracted:
 [99 88 40 50]
Compressed:
 [99 88 40 50]


In [71]:
# np.choose()
choices = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
choice = np.choose([2, 1, 0], choices)
print("Chosen:\n", choice)

# np.ix_()
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 11, 12])
ix = np.ix_(arr1, arr2)
print("ix_:\n", ix)

# np.indices()
indices = np.indices((2, 3))
print("Indices:\n", indices)

# np.meshgrid()
x = np.array([1, 2, 3])
y = np.array([4, 5])
xx, yy = np.meshgrid(x, y)
print("Meshgrid x:\n", xx)
print("Meshgrid y:\n", yy)

Chosen:
 [70 50 30]
ix_:
 (array([[1],
       [2],
       [3]]), array([[10, 11, 12]]))
Indices:
 [[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
Meshgrid x:
 [[1 2 3]
 [1 2 3]]
Meshgrid y:
 [[4 4 4]
 [5 5 5]]


#Slicing 1D, 2D, and 3D arrays

In [74]:
import numpy as np

# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])  # Output: 10
print(arr[2])  # Output: 30
print(arr[-1]) # Output: 50


10
30
50


In [75]:
# Slicing
print(arr[1:4])  # Output: [20 30 40]
print(arr[:3])   # Output: [10 20 30]
print(arr[2:])   # Output: [30 40 50]
print(arr[::2])  # Output: [10 30 50]

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


In [73]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print(arr_2d[0, 0])  # Output: 1
print(arr_2d[1, 2])  # Output: 6
print(arr_2d[-1, -1]) # Output: 9

1
6
9


#3D array Indexing & Slicing

In [76]:
import numpy as np

# Creating a 3D array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])
print("Original array:\n", arr_3d)


Original array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [77]:
# Accessing a single element
print(arr_3d[0, 1, 2])  # Output: 6
print(arr_3d[2, 0, 1])  # Output: 14

6
14


In [81]:
# Slicing along each axis
print("Slicing along first axis",arr_3d[1:, :, :])  # Slices the first axis
# Output:
# [[[ 7  8  9]
#   [10 11 12]]
#  [[13 14 15]
#   [16 17 18]]]

print("Slicing along the second axis",arr_3d[:, 0, :])  # Slices the second axis
# Output:
# [[ 1  2  3]
#  [ 7  8  9]
#  [13 14 15]]

print("Slicing along the thrid axis",arr_3d[:, :, 1])  # Slices the third axis
# Output:
# [[ 2  5]
#  [ 8 11]
#  [14 17]]


Slicing along first axis [[[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Slicing along the second axis [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Slicing along the thrid axis [[ 2  5]
 [ 8 11]
 [14 17]]


#Mathematical & Trignometric Functions

In [82]:
import numpy as np

# Arrays for operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# np.add()
add_result = np.add(a, b)
print("Add:\n", add_result)

# np.subtract()
subtract_result = np.subtract(a, b)
print("Subtract:\n", subtract_result)

# np.multiply()
multiply_result = np.multiply(a, b)
print("Multiply:\n", multiply_result)

# np.divide()
divide_result = np.divide(b, a)
print("Divide:\n", divide_result)

# np.power()
power_result = np.power(a, 2)
print("Power:\n", power_result)

# np.mod()
mod_result = np.mod(b, a)
print("Mod:\n", mod_result)

# np.remainder()
remainder_result = np.remainder(b, a)
print("Remainder:\n", remainder_result)

# np.absolute()
absolute_result = np.absolute(np.array([-1, -2, -3]))
print("Absolute:\n", absolute_result)

# np.sqrt()
sqrt_result = np.sqrt(a)
print("Sqrt:\n", sqrt_result)

# np.exp()
exp_result = np.exp(a)
print("Exp:\n", exp_result)

# np.log()
log_result = np.log(a + 1)  # Adding 1 to avoid log(0)
print("Log:\n", log_result)

# np.log10()
log10_result = np.log10(a + 1)
print("Log10:\n", log10_result)

# np.log2()
log2_result = np.log2(a + 1)
print("Log2:\n", log2_result)

# np.sin()
sin_result = np.sin(np.array([0, np.pi/2, np.pi]))
print("Sin:\n", sin_result)

# np.cos()
cos_result = np.cos(np.array([0, np.pi/2, np.pi]))
print("Cos:\n", cos_result)

# np.tan()
tan_result = np.tan(np.array([0, np.pi/4, np.pi/2]))
print("Tan:\n", tan_result)

# np.arcsin()
arcsin_result = np.arcsin(np.array([0, 0.5, 1]))
print("Arcsin:\n", arcsin_result)

# np.arccos()
arccos_result = np.arccos(np.array([1, 0.5, 0]))
print("Arccos:\n", arccos_result)

# np.arctan()
arctan_result = np.arctan(np.array([0, 1, -1]))
print("Arctan:\n", arctan_result)

# np.arctan2()
arctan2_result = np.arctan2(np.array([1, 1, 1]), np.array([1, -1, 0]))
print("Arctan2:\n", arctan2_result)

# np.sinh()
sinh_result = np.sinh(np.array([0, 1, -1]))
print("Sinh:\n", sinh_result)

# np.cosh()
cosh_result = np.cosh(np.array([0, 1, -1]))
print("Cosh:\n", cosh_result)

# np.tanh()
tanh_result = np.tanh(np.array([0, 1, -1]))
print("Tanh:\n", tanh_result)

# np.arcsinh()
arcsinh_result = np.arcsinh(np.array([0, 1, -1]))
print("Arcsinh:\n", arcsinh_result)

# np.arccosh()
arccosh_result = np.arccosh(np.array([1, 2, 3]))
print("Arccosh:\n", arccosh_result)

# np.arctanh()
arctanh_result = np.arctanh(np.array([0, 0.5, -0.5]))
print("Arctanh:\n", arctanh_result)

Add:
 [5 7 9]
Subtract:
 [-3 -3 -3]
Multiply:
 [ 4 10 18]
Divide:
 [4.  2.5 2. ]
Power:
 [1 4 9]
Mod:
 [0 1 0]
Remainder:
 [0 1 0]
Absolute:
 [1 2 3]
Sqrt:
 [1.         1.41421356 1.73205081]
Exp:
 [ 2.71828183  7.3890561  20.08553692]
Log:
 [0.69314718 1.09861229 1.38629436]
Log10:
 [0.30103    0.47712125 0.60205999]
Log2:
 [1.        1.5849625 2.       ]
Sin:
 [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos:
 [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan:
 [0.00000000e+00 1.00000000e+00 1.63312394e+16]
Arcsin:
 [0.         0.52359878 1.57079633]
Arccos:
 [0.         1.04719755 1.57079633]
Arctan:
 [ 0.          0.78539816 -0.78539816]
Arctan2:
 [0.78539816 2.35619449 1.57079633]
Sinh:
 [ 0.          1.17520119 -1.17520119]
Cosh:
 [1.         1.54308063 1.54308063]
Tanh:
 [ 0.          0.76159416 -0.76159416]
Arcsinh:
 [ 0.          0.88137359 -0.88137359]
Arccosh:
 [0.         1.3169579  1.76274717]
Arctanh:
 [ 0.          0.54930614 -0.54930614]


#Statisical functions

In [85]:
import numpy as np

# Sample data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# np.mean()
mean = np.mean(data)
print("Mean:\n", mean)

# np.median()
median = np.median(data)
print("Median:\n", median)

# np.average()
average = np.average(data)
print("Average:\n", average)

# np.std()
std_dev = np.std(data)
print("Standard Deviation:\n", std_dev)

# np.var()
variance = np.var(data)
print("Variance:\n", variance)

# np.min()
minimum = np.min(data)
print("Min:\n", minimum)

# np.max()
maximum = np.max(data)
print("Max:\n", maximum)

# np.ptp()
range_ptp = np.ptp(data)
print("Peak-to-Peak (Range):\n", range_ptp)

# np.percentile()
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("25th Percentile:\n", percentile_25)
print("75th Percentile:\n", percentile_75)

# np.quantile()
quantile_0_25 = np.quantile(data, 0.25)
quantile_0_75 = np.quantile(data, 0.75)
print("0.25 Quantile:\n", quantile_0_25)
print("0.75 Quantile:\n", quantile_0_75)

# np.histogram()
hist, bin_edges = np.histogram(data, bins=5)
print("Histogram:\n", hist)
print("Bin Edges:\n", bin_edges)

# np.bincount()
bincount = np.bincount(data)
print("Bincount:\n", bincount)

# np.cov()
covariance = np.cov(data_2d, rowvar=False)
print("Covariance Matrix:\n", covariance)

# np.correlate()
correlation = np.correlate(data, data, mode='full')
print("Correlation:\n", correlation)

# np.corrcoef()
correlation_coef = np.corrcoef(data_2d)
print("Correlation Coefficient Matrix:\n", correlation_coef)


Mean:
 5.5
Median:
 5.5
Average:
 5.5
Standard Deviation:
 2.8722813232690143
Variance:
 8.25
Min:
 1
Max:
 10
Peak-to-Peak (Range):
 9
25th Percentile:
 3.25
75th Percentile:
 7.75
0.25 Quantile:
 3.25
0.75 Quantile:
 7.75
Histogram:
 [2 2 2 2 2]
Bin Edges:
 [ 1.   2.8  4.6  6.4  8.2 10. ]
Bincount:
 [0 1 1 1 1 1 1 1 1 1 1]
Covariance Matrix:
 [[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
Correlation:
 [ 10  29  56  90 130 175 224 276 330 385 330 276 224 175 130  90  56  29
  10]
Correlation Coefficient Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
